const express = require("express");
const router = express.Router();
const nodemailer = require("nodemailer");
const PurchaseOrder = require("../models/PurchaseOrder");
const Medicine = require("../models/Medicine");
const Supplier = require("../models/Supplier");
const protect = require("../middleware/authMiddleware");

const getTransporter = () =>
  nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 587,
    secure: false,
    requireTLS: true,
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
    tls: {
      rejectUnauthorized: false,
    },
  });

// Get all purchase orders
router.get("/", protect, async (req, res) => {
  try {
    const orders = await PurchaseOrder.find().sort({ createdAt: -1 });
    res.json(orders);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Update order — supplier, orderQty, status
router.put("/:id", protect, async (req, res) => {
  try {
    const { status, supplierId, orderQty } = req.body;
    const order = await PurchaseOrder.findById(req.params.id);
    if (!order) return res.status(404).json({ message: "Order not found" });

    if (supplierId) {
      const supplier = await Supplier.findById(supplierId);
      if (supplier) {
        order.supplier = supplier._id;
        order.supplierName = supplier.name;
        order.supplierEmail = supplier.email || "";
        order.supplierContact = supplier.contact || "";
      }
    }

    if (orderQty && orderQty > 0) order.orderQty = orderQty;

    if (status) {
      order.status = status;
      if (status === "Received") {
        await Medicine.findByIdAndUpdate(order.medicine, {
          $inc: { quantity: order.orderQty },
        });
      }
    }

    await order.save();
    res.json(order);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Send email to supplier
router.post("/:id/send-email", protect, async (req, res) => {
  try {
    const order = await PurchaseOrder.findById(req.params.id);
    if (!order) return res.status(404).json({ message: "Order not found" });

    if (!order.supplierEmail)
      return res.status(400).json({ message: "Supplier has no email. Edit the supplier and add an email first." });

    const date = new Date().toLocaleDateString("en-IN");
    const subject = `Purchase Order Request — ${order.medicineName}`;
    const body =
`Dear ${order.supplierName},

We would like to place a purchase order for the following medicine:

  Medicine      : ${order.medicineName}
  Order Qty     : ${order.orderQty} units
  Current Stock : ${order.currentStock} units
  Order Date    : ${date}

Kindly process this order at the earliest and confirm the delivery schedule.

Regards,
Pharmacy Inventory Management
Email: ${process.env.EMAIL_USER}`;

    const transporter = getTransporter();

    await transporter.sendMail({
      from: `"Pharmacy Inventory" <${process.env.EMAIL_USER}>`,
      to: order.supplierEmail,
      subject,
      text: body,
    });

    order.emailLog = { sent: true, sentAt: new Date(), subject, body };
    await order.save();

    res.json({ message: `Email sent to ${order.supplierEmail}`, order });
  } catch (err) {
    console.error("Email error:", err.message);
    res.status(500).json({ error: err.message });
  }
});

// Manual order creation
router.post("/", protect, async (req, res) => {
  try {
    const { medicineId, supplierId, orderQty } = req.body;
    if (!medicineId || !orderQty)
      return res.status(400).json({ message: "Medicine and order quantity are required" });

    const medicine = await Medicine.findById(medicineId);
    if (!medicine) return res.status(404).json({ message: "Medicine not found" });

    let supplierData = { supplier: null, supplierName: "Unassigned", supplierEmail: "", supplierContact: "" };
    const resolvedSupplierId = supplierId || medicine.supplier;
    if (resolvedSupplierId) {
      const supplier = await Supplier.findById(resolvedSupplierId);
      if (supplier) {
        supplierData = {
          supplier: supplier._id,
          supplierName: supplier.name,
          supplierEmail: supplier.email || "",
          supplierContact: supplier.contact || "",
        };
      }
    }

    const order = await PurchaseOrder.create({
      medicine: medicine._id,
      medicineName: medicine.name,
      ...supplierData,
      currentStock: medicine.quantity,
      orderQty,
      autoGenerated: false,
    });

    res.status(201).json(order);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Delete order
router.delete("/:id", protect, async (req, res) => {
  try {
    await PurchaseOrder.findByIdAndDelete(req.params.id);
    res.json({ message: "Order deleted" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
