const express = require("express");
const router = express.Router();
const Sale = require("../models/Sale");
const Medicine = require("../models/Medicine");
const PurchaseOrder = require("../models/PurchaseOrder");
const protect = require("../middleware/authMiddleware");

// Get all sales
router.get("/", protect, async (req, res) => {
  try {
    const sales = await Sale.find().sort({ createdAt: -1 });
    res.json(sales);
  } catch (err) {
    console.error("GET /sales error:", err.message);
    res.status(500).json({ error: err.message });
  }
});

// Get single sale
router.get("/:id", protect, async (req, res) => {
  try {
    const sale = await Sale.findById(req.params.id);
    if (!sale) return res.status(404).json({ message: "Sale not found" });
    res.json(sale);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Create bill
router.post("/", protect, async (req, res) => {
  try {
    const { customerName, customerMobile, items, subTotal, gstAmount, grandTotal } = req.body;

    if (!customerName || !customerMobile)
      return res.status(400).json({ message: "Customer name and mobile are required" });

    if (!items || items.length === 0)
      return res.status(400).json({ message: "At least one medicine is required" });

    const billItems = [];

    for (const item of items) {
      const medicine = await Medicine.findById(item.medicineId).populate("supplier");
      if (!medicine)
        return res.status(404).json({ message: `Medicine not found: ${item.medicineId}` });

      if (medicine.quantity < item.quantity)
        return res.status(400).json({
          message: `Insufficient stock for "${medicine.name}". Available: ${medicine.quantity}`,
        });

      // Deduct stock
      medicine.quantity -= item.quantity;
      await medicine.save();

      // Auto purchase order if stock drops below reorderLevel
      const reorderLevel = medicine.reorderLevel ?? 25;
      if (medicine.quantity < reorderLevel) {
        // Only create if no pending order already exists for this medicine
        const existingOrder = await PurchaseOrder.findOne({
          medicine: medicine._id,
          status: "Pending",
        });

        if (!existingOrder) {
          await PurchaseOrder.create({
            medicine: medicine._id,
            medicineName: medicine.name,
            supplier: medicine.supplier?._id || null,
            supplierName: medicine.supplier?.name || "Unassigned",
            currentStock: medicine.quantity,
            orderQty: medicine.reorderQty ?? 50,
            autoGenerated: true,
          });
          console.log(`Auto purchase order created for "${medicine.name}" (stock: ${medicine.quantity})`);
        }
      }

      billItems.push({
        medicineId: medicine._id,
        medicineName: medicine.name,
        price: medicine.price,
        discount: item.discount || 0,
        discountedPrice: item.discountedPrice != null ? item.discountedPrice : medicine.price,
        quantity: item.quantity,
        totalPrice: item.totalPrice,
      });
    }

    const sale = new Sale({
      customerName,
      customerMobile,
      items: billItems,
      subTotal: subTotal || 0,
      gstAmount: gstAmount || 0,
      grandTotal,
    });

    await sale.save();
    res.status(201).json(sale);
  } catch (err) {
    console.error("POST /sales error:", err.message);
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
