const mongoose = require("mongoose");

const purchaseOrderSchema = new mongoose.Schema(
  {
    medicine: { type: mongoose.Schema.Types.ObjectId, ref: "Medicine", required: true },
    medicineName: { type: String, required: true },
    supplier: { type: mongoose.Schema.Types.ObjectId, ref: "Supplier" },
    supplierName: { type: String, default: "Unassigned" },
    supplierEmail: { type: String, default: "" },
    supplierContact: { type: String, default: "" },
    currentStock: { type: Number, required: true },
    orderQty: { type: Number, required: true },
    status: { type: String, enum: ["Pending", "Approved", "Received"], default: "Pending" },
    autoGenerated: { type: Boolean, default: true },
    emailLog: {
      sent: { type: Boolean, default: false },
      sentAt: { type: Date },
      subject: { type: String },
      body: { type: String },
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("PurchaseOrder", purchaseOrderSchema);
